Bug fixing on state/modes, combined fragments, seq messages
eclipse/capella-textual-editor pull request #10
Opened 2020-10-14 13:12 UTC by georgiana-ecobici

Change-Id: I0000000000000000000000000000000000000000
Signed-off-by: Georgiana Ecobici <georgiana-elena.ecobici@thalesgroup.com>

2020-10-20 08:34 UTC, claudiasima-ro approved these changes

2020-10-20 15:18 UTC, minhtutonthat requested changes
- Could you resolve Sonar issues in all the (not generated) code, especially:
	+ unnecessary if clauses
	+ unused parameters
	
- Could you go through method parameters' name (especially in the 2 classes DiagramToXtextCommands and XtextToDiagramCommands) and document them in the code because it's quite hard sometimes to follow and thus difficult to maintain later. This is just an example but could you do the same thing for other methods to make the code more readable? I would change 
org.polarsys.capella.scenario.editor.embeddededitor.commands.DiagramToXtextCommands.generateMessages(Object[] ends, 
      int i,
      Stack<Message> messagesToDeactivate,
      Stack<CombinedFragment> combinedFragments, Stack<Block> blockOperands, EList<EObject> elements,
      TextualScenarioFactory factory) 
to something like:
  /**
   * 
   * @param allCapellaEnds all input ends coming from the input diagram
   * @param messageEndPosition current message end position in all input ends
   * @param messagesToDeactivate to keep track of messages to deactivate
   * @param xtextBlockOperands to keep track of currently being processed output block operand
   * @param xtextElements the list of all output language elements
   * @param factory
   * @return the next input end to be processed
   */
org.polarsys.capella.scenario.editor.embeddededitor.commands.DiagramToXtextCommands.generateMessages(Object[] allCapellaEnds, 
      int messageEndPosition,
      Stack<Message> messagesToDeactivate,
      Stack<Block> xtextBlockOperands, 
	  EList<EObject> xtextElements,
      TextualScenarioFactory factory)
	
- Change the name of the method org.polarsys.capella.scenario.editor.embeddededitor.commands.DiagramToXtextCommands.generateActors(Model, Scenario, TextualScenarioFactory)
=> generateParticipants

- Similarly a lot of methods do not have comments about what they do even though their name do not give a clear idea either.

2020-10-20 15:18 UTC, minhtutonthat commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/DiagramToXtextCommands.java
> +      Stack<Message> messagesToDeactivate,
Could you use fully qualified name for classes coming form the DSL to distinguish from those coming from Capella?

2020-10-20 15:18 UTC, minhtutonthat commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
> +   * Remove from diagram all combined fragment related to the participant that has just been deleted
Please update the documentation of this method.

2020-10-20 15:18 UTC, minhtutonthat commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
> +  private static List<TimeLapse> getStateFragmentsWithGivenInstanceRoleAndRelatedElement(Scenario scenario,
Could you get a shorter name for the method and document what it does in the comment?

2020-10-20 15:18 UTC, minhtutonthat commented on plugins/org.polarsys.capella.scenario.editor.embeddededitor/src/org/polarsys/capella/scenario/editor/embeddededitor/commands/XtextToDiagramCommands.java
> +    List<EObject> simillarStateFragments = previousEditorStateFragments.stream()
This is an example of the complexity of the code when processing edge cases without any comment. I just have no idea why do we have to lood at similar StateFragments while creating new StateFragment here.

2020-10-26 07:44 UTC, minhtutonthat approved these changes

2020-10-26 07:44 UTC, merged